version: "3.8"
services:
  django_app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django_app:djainga
    container_name: djainga_container
    command: python manage.py runserver 0.0.0.0:8000
